# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=250, null=True, verbose_name='Name On Card')),
                ('cardNumber', models.CharField(max_length=20, null=True, verbose_name='Card Number')),
                ('expirationDateMM', models.IntegerField(verbose_name='expiration Date (MM)')),
                ('expirationDateYY', models.IntegerField(verbose_name='expiration Date (YY)')),
                ('cvcCode', models.IntegerField(verbose_name='CVV Code')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=250, verbose_name='State')),
                ('zipCode', models.CharField(blank=True, max_length=250, verbose_name='Zip Code')),
                ('cardshortname', models.CharField(max_length=25, null=True, verbose_name='Card short Name')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
