# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentsDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nameOnCard', models.CharField(max_length=250, null=True)),
                ('cardNumber', models.CharField(max_length=20, null=True)),
                ('expirationDateMM', models.IntegerField()),
                ('expirationDateYY', models.IntegerField()),
                ('cvcCode', models.IntegerField()),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('zipCode', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
