# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsdetails',
            name='cardshortname',
            field=models.CharField(max_length=25, null=True, verbose_name='Card short Name'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='cardNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='cvcCode',
            field=models.IntegerField(verbose_name='CVV Code'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='expirationDateMM',
            field=models.IntegerField(verbose_name='expiration Date (MM)'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='expirationDateYY',
            field=models.IntegerField(verbose_name='expiration Date (YY)'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='nameOnCard',
            field=models.CharField(max_length=250, null=True, verbose_name='Name On Card'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='state',
            field=models.CharField(blank=True, max_length=250, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='paymentsdetails',
            name='zipCode',
            field=models.CharField(blank=True, max_length=250, verbose_name='Zip Code'),
        ),
    ]
