# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsdetails',
            name='lymo_company_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
