# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ridebooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_long', models.CharField(max_length=250, null=True)),
                ('pickup_lat', models.CharField(max_length=250, null=True)),
                ('drop_lat', models.CharField(max_length=250, null=True)),
                ('drop_long', models.CharField(max_length=250, null=True)),
                ('pickup_address', models.CharField(max_length=250, null=True)),
                ('drop_address', models.CharField(max_length=250, null=True)),
                ('ride_datetime', models.CharField(max_length=50, null=True)),
                ('passenger', models.CharField(max_length=250, null=True)),
                ('passenger_email', models.CharField(max_length=250, null=True)),
                ('vehicle_type', models.CharField(max_length=250, null=True)),
                ('noof_passengers', models.CharField(max_length=250, null=True)),
                ('ride_booked_by', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
