# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20170817_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='ride_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
