# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ridebooking_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='passenger_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
