# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='addressLine1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='addressLine2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='companyName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='zipCode',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
