# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170816_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='addressLine2',
        ),
    ]
