# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170821_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='userType',
            field=models.CharField(choices=[('company_secretary', 'company Secretary'), ('third_party_desk', 'Third party travel desk Secretary')], default='company_secretary', max_length=50),
        ),
    ]
