# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_companydetails_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='address',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='city',
            field=models.CharField(blank=True, max_length=250, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='companyName',
            field=models.CharField(max_length=250, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='country',
            field=models.CharField(blank=True, max_length=250, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='state',
            field=models.CharField(blank=True, max_length=250, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='userType',
            field=models.CharField(choices=[('company_secretary', 'company Secretary'), ('third_party_desk', 'Third party travel desk Secretary')], default='company_secretary', max_length=50, verbose_name='user Type'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='zipCode',
            field=models.CharField(blank=True, max_length=250, verbose_name='zip Code'),
        ),
    ]
