# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lymo_user_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
