# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_lymo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='lymo_company_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='lymousine_company_id'),
        ),
    ]
